apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels:
    app.kubernetes.io/component: mongodb
    {{- include "recipes.labels" . | nindent 4}}
type: Opaque
data:
  recipes_db_url: {{ .Values.recipesMongoUrl | b64enc }}
