apiVersion: v1
kind: Service
metadata:
  name: recipes
  labels:
    {{- include "recipes.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app.kubernetes.io/name: recipes
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
