apiVersion: v1
kind: Service
metadata:
  name: recipes
  labels:
    {{- include "recipes.labels" . | nindent 4 }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app.kubernetes.io/name: recipes
    app.kubernetes.io/instance: {{ .Release.Name }}
  clusterIP: 10.152.0.7
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
