user:
  api/v1/recipes/{id}:
    "read:any": ["*"]
    "update:own": ["*"]
    "delete:own": ["*"]
  api/v1/recipes:
    "read:any": ["*"]
    "create:own": ["*"]
admin:
  api/v1/recipes:
    "read:any": ["*"]
    "create:any": ["*"]
  api/v1/recipes/{id}:
    "read:any": ["*"]
    "update:any": ["*"]
    "delete:any": ["*"]