name: Okteto Deployment

on:
  push:
    branches: [ develop ]
  
jobs:
  test:
    uses: resinas/contacts-service/.github/workflows/tests.yml@testing
    
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Okteto login
      uses: okteto/login@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
        
    - name: Okteto Deploy
      uses: resinas/okteto-push@v1.0.2
      with:
        namespace: yyrecipes-josaloroc
        build: true
